import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="bg-blue-900 min-h-screen flex">
        <SessionProvider session={session}>
          <Nav />
          <div className=" bg-white flex flex-grow mt-2 mr-2 rounded-lg p-4 mb-2">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
